# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cortex',
                'doc_host': 'https://CptCaptain.github.io',
                'git_url': 'https://github.com/CptCaptain/cortex',
                'lib_path': 'cortex'},
  'syms': {'cortex.core': {'cortex.core.foo': ('core.html#foo', 'cortex/core.py')}}}
